server:
  port: 8021
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/nonFaceToFace?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.nftf.kys.dto
custom:
  logging:
    dir: log
    level: debug